package AplikasiPenjualanKopi;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author hadad
 */
public class AplikasiKopi extends javax.swing.JFrame {

    private DefaultTableModel Model;
    private String namapemesan;

    /**
     * Creates new form AplikasiKopi
     */
    public AplikasiKopi() {
        initComponents();
        MenungguTransaksiTabel.setRowHeight(30); 
        MenungguTransaksiTabel.setShowVerticalLines(false); 

        TransaksiTerbayarTabel.setRowHeight(30);

        loadDataMenunggu(); 
        loadDataTerbayar(); 
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CaramelLatteCb = new javax.swing.JCheckBox();
        AmericanoCb = new javax.swing.JCheckBox();
        FreezyDutchCb = new javax.swing.JCheckBox();
        MatchaLatteCb = new javax.swing.JCheckBox();
        HargaCaramelLatteTxt = new javax.swing.JTextField();
        HargaAmericanoTxt = new javax.swing.JTextField();
        MetodePembayaranCbx = new javax.swing.JComboBox<>();
        HargaFreezyDutchTxt = new javax.swing.JTextField();
        HargaMatchaLatteTxt = new javax.swing.JTextField();
        NamaPemesanTxt = new javax.swing.JTextField();
        JumlahCaramelLatteTxt = new javax.swing.JTextField();
        JumlahAmericanoTxt = new javax.swing.JTextField();
        JumlahFreezyDutchTxt = new javax.swing.JTextField();
        JumlahMatchaLatteTxt = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        SubTotalCaramelTxt = new javax.swing.JTextField();
        SubTotalAmericanoTxt = new javax.swing.JTextField();
        SubTotalFreezyTxt = new javax.swing.JTextField();
        SubTotalMatchaTxt = new javax.swing.JTextField();
        HapusButton = new javax.swing.JButton();
        KonfirmasiButton = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        DiskonTxt = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        TotalTxt = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        TotalBayarTxt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        MenungguTransaksiTabel = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        ProsesBayarButton = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        TransaksiTerbayarTabel = new javax.swing.JTable();
        KeluarButton = new javax.swing.JButton();
        ResetButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("FORM PEMESANAN KOPI - HADAD AL TAMI_221011400718");
        setBackground(new java.awt.Color(255, 255, 255));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setName(""); // NOI18N

        jLabel1.setText("Nama Pembeli");

        jLabel2.setText("Metode Pembayaran");

        jLabel3.setText("Menu Kopi");

        jLabel4.setText("Harga");

        jLabel5.setText("Jumlah");

        CaramelLatteCb.setText("Caramel Latte");
        CaramelLatteCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaramelLatteCbActionPerformed(evt);
            }
        });

        AmericanoCb.setText("Americano ");
        AmericanoCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AmericanoCbActionPerformed(evt);
            }
        });

        FreezyDutchCb.setText("Freezy Dutch Chocolate ");
        FreezyDutchCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FreezyDutchCbActionPerformed(evt);
            }
        });

        MatchaLatteCb.setText("Matcha Latte");
        MatchaLatteCb.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MatchaLatteCbActionPerformed(evt);
            }
        });

        HargaCaramelLatteTxt.setEditable(false);

        HargaAmericanoTxt.setEditable(false);

        MetodePembayaranCbx.setModel(new javax.swing.DefaultComboBoxModel<>(new String[]{"==PILIH==", "Cash", "QRIS", "GoPay", "DANA"}));
        MetodePembayaranCbx.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MetodePembayaranCbxActionPerformed(evt);
            }
        });

        HargaFreezyDutchTxt.setEditable(false);

        HargaMatchaLatteTxt.setEditable(false);
        HargaMatchaLatteTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HargaMatchaLatteTxtActionPerformed(evt);
            }
        });

        jLabel6.setText("Sub Total");

        SubTotalCaramelTxt.setEditable(false);

        SubTotalAmericanoTxt.setEditable(false);

        SubTotalFreezyTxt.setEditable(false);
        SubTotalFreezyTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SubTotalFreezyTxtActionPerformed(evt);
            }
        });

        SubTotalMatchaTxt.setEditable(false);

        HapusButton.setBackground(new java.awt.Color(255, 51, 51));
        HapusButton.setText("HAPUS");
        HapusButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HapusButtonActionPerformed(evt);
            }
        });

        KonfirmasiButton.setBackground(new java.awt.Color(102, 255, 102));
        KonfirmasiButton.setText("KONFIRMASI");
        KonfirmasiButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KonfirmasiButtonActionPerformed(evt);
            }
        });

        jLabel7.setText("Diskon");

        DiskonTxt.setEditable(false);
        DiskonTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        DiskonTxt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiskonTxtActionPerformed(evt);
            }
        });

        jLabel8.setText("Total");

        TotalTxt.setEditable(false);
        TotalTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel9.setText("Total Bayar");

        TotalBayarTxt.setEditable(false);
        TotalBayarTxt.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        MenungguTransaksiTabel.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String[]{
                    "Nama Pembeli", "Menu Kopi", "Harga", "Jumlah", "Total Bayar", "Metode Pembayaran", "Status"
                }
        ));
        jScrollPane1.setViewportView(MenungguTransaksiTabel);

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("APLIKASI PEMESANAN KOPI");

        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Menunggu Transaksi Pembayaran");

        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel12.setText("Transaksi Terbayar");

        ProsesBayarButton.setBackground(new java.awt.Color(102, 255, 204));
        ProsesBayarButton.setText("PROSES BAYAR");
        ProsesBayarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ProsesBayarButtonActionPerformed(evt);
            }
        });

        TransaksiTerbayarTabel.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][]{
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null},
                    {null, null, null, null, null, null, null}
                },
                new String[]{
                    "Nama Pembeli", "Menu Kopi", "Harga", "Jumlah", "Total Bayar", "Metode Pembayaran", "Status"
                }
        ));
        jScrollPane3.setViewportView(TransaksiTerbayarTabel);

        KeluarButton.setBackground(new java.awt.Color(204, 204, 204));
        KeluarButton.setFont(new java.awt.Font("Verdana", 0, 12)); // NOI18N
        KeluarButton.setText("KELUAR");
        KeluarButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                KeluarButtonActionPerformed(evt);
            }
        });

        ResetButton.setText("RESET");
        ResetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ResetButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(111, 111, 111)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(DiskonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(144, 144, 144)
                                                                        .addComponent(TotalBayarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(126, 126, 126))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                                                .addComponent(HargaAmericanoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addGroup(layout.createSequentialGroup()
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addComponent(CaramelLatteCb)
                                                                                                .addComponent(AmericanoCb)
                                                                                                .addComponent(FreezyDutchCb)
                                                                                                .addComponent(MatchaLatteCb)
                                                                                                .addComponent(ResetButton))
                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                .addGroup(layout.createSequentialGroup()
                                                                                                        .addGap(78, 78, 78)
                                                                                                        .addComponent(HargaCaramelLatteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                                                .addComponent(HargaFreezyDutchTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                                                .addComponent(HargaMatchaLatteTxt, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                                                                        .addGap(46, 46, 46)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(JumlahAmericanoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JumlahFreezyDutchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JumlahMatchaLatteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                                .addComponent(JumlahCaramelLatteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                                                        .addGap(49, 49, 49)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                                                                .addComponent(SubTotalMatchaTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(SubTotalFreezyTxt, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 176, Short.MAX_VALUE)
                                                                                .addComponent(SubTotalAmericanoTxt, javax.swing.GroupLayout.Alignment.LEADING)
                                                                                .addComponent(SubTotalCaramelTxt, javax.swing.GroupLayout.Alignment.LEADING)))
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(12, 12, 12)
                                                                        .addComponent(jLabel3)
                                                                        .addGap(206, 206, 206)
                                                                        .addComponent(jLabel4)
                                                                        .addGap(110, 110, 110)
                                                                        .addComponent(jLabel5)
                                                                        .addGap(126, 126, 126)
                                                                        .addComponent(jLabel6))
                                                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                        .addComponent(jLabel7)
                                                                        .addGap(84, 84, 84)
                                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                                .addComponent(KonfirmasiButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                                                .addComponent(TotalTxt))
                                                                        .addGap(56, 56, 56)
                                                                        .addComponent(jLabel9)
                                                                        .addGap(171, 171, 171)))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addComponent(jLabel8)
                                                                .addGap(319, 319, 319))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(43, 43, 43)
                                                .addComponent(KeluarButton)
                                                .addGap(53, 53, 53)
                                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(NamaPemesanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addGap(96, 96, 96)
                                                .addComponent(jLabel2)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(MetodePembayaranCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(14, 14, 14)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel10)
                                                                .addGap(315, 315, 315))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(343, 343, 343))
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jLabel11)
                                                                .addGap(309, 309, 309))
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                                                .addGroup(layout.createSequentialGroup()
                                                                        .addGap(328, 328, 328)
                                                                        .addComponent(HapusButton, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                        .addGap(32, 32, 32)
                                                                        .addComponent(ProsesBayarButton))
                                                                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 885, Short.MAX_VALUE)
                                                                .addComponent(jScrollPane1)))))
                                .addContainerGap(15, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel10)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                        .addComponent(jLabel1)
                                                        .addComponent(NamaPemesanTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addComponent(jLabel2)
                                                        .addComponent(MetodePembayaranCbx, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(9, 9, 9)
                                                .addComponent(KeluarButton)))
                                .addGap(29, 29, 29)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(jLabel3)
                                        .addComponent(jLabel4)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(CaramelLatteCb)
                                        .addComponent(HargaCaramelLatteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JumlahCaramelLatteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SubTotalCaramelTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(AmericanoCb)
                                        .addComponent(HargaAmericanoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JumlahAmericanoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SubTotalAmericanoTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(16, 16, 16)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(FreezyDutchCb)
                                        .addComponent(HargaFreezyDutchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JumlahFreezyDutchTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SubTotalFreezyTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(MatchaLatteCb)
                                        .addComponent(HargaMatchaLatteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(JumlahMatchaLatteTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(SubTotalMatchaTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addGap(52, 52, 52)
                                                                .addComponent(jLabel9))
                                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                                .addComponent(jLabel7)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                        .addComponent(TotalBayarTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                                                .addComponent(DiskonTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addComponent(ResetButton))))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(18, 18, 18)
                                                .addComponent(jLabel8)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(TotalTxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(KonfirmasiButton)
                                .addGap(26, 26, 26)
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(HapusButton)
                                        .addComponent(ProsesBayarButton))
                                .addGap(24, 24, 24)
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void HapusButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HapusButtonActionPerformed
        int selectedRow = MenungguTransaksiTabel.getSelectedRow();

        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data yang ingin dihapus!");
            return;
        }

        // Konfirmasi penghapusan
        int konfirmasi = JOptionPane.showConfirmDialog(this, "Yakin ingin di hapus?", "Konfirmasi", JOptionPane.YES_NO_OPTION);
        if (konfirmasi != JOptionPane.YES_OPTION) {
            return;
        }

        // Ambil data dari baris yang dipilih
        String namaPemesan = MenungguTransaksiTabel.getValueAt(selectedRow, 0).toString();
        String menu = MenungguTransaksiTabel.getValueAt(selectedRow, 1).toString();
        String totalBayar = MenungguTransaksiTabel.getValueAt(selectedRow, 4).toString();

        // Hapus dari database
        try {
            Connection conn = Koneksidatabase.getConnection();
            String sql = "DELETE FROM pesanan WHERE nama_pemesan=? AND menu=? AND total_bayar=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaPemesan);
            pst.setString(2, menu);
            pst.setString(3, totalBayar);

            int affectedRows = pst.executeUpdate();

            if (affectedRows > 0) {
                // Hapus dari tabel GUI
                DefaultTableModel model = (DefaultTableModel) MenungguTransaksiTabel.getModel();
                model.removeRow(selectedRow);
                JOptionPane.showMessageDialog(this, "Data berhasil dihapus!");
            } else {
                JOptionPane.showMessageDialog(this, "Gagal menghapus dari database. Data tidak ditemukan.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error saat menghapus dari database: " + e.getMessage());
        }
    }//GEN-LAST:event_HapusButtonActionPerformed

    private void DiskonTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiskonTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiskonTxtActionPerformed

    private void SubTotalFreezyTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SubTotalFreezyTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SubTotalFreezyTxtActionPerformed

    private void KonfirmasiButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KonfirmasiButtonActionPerformed
        String namaPemesan = NamaPemesanTxt.getText();
        String metodepembayaran = (String) MetodePembayaranCbx.getSelectedItem();

        StringBuilder menuBuilder = new StringBuilder();
        StringBuilder hargaBuilder = new StringBuilder();
        StringBuilder jumlahBuilder = new StringBuilder();

        int grandTotal = 0;

        // Freezy Dutch Chocolate
        if (!HargaFreezyDutchTxt.getText().isEmpty() && !JumlahFreezyDutchTxt.getText().isEmpty()) {
            int harga = Integer.parseInt(HargaFreezyDutchTxt.getText());
            int jumlah = Integer.parseInt(JumlahFreezyDutchTxt.getText());
            int total = harga * jumlah;
            grandTotal += total;

            menuBuilder.append("Freezy Dutch Chocolate").append(", ");
            hargaBuilder.append(harga).append(", ");
            jumlahBuilder.append("x").append(jumlah).append(", ");

            SubTotalFreezyTxt.setText(String.valueOf(total));
        }

        // Caramel Latte
        if (!HargaCaramelLatteTxt.getText().isEmpty() && !JumlahCaramelLatteTxt.getText().isEmpty()) {
            int harga = Integer.parseInt(HargaCaramelLatteTxt.getText());
            int jumlah = Integer.parseInt(JumlahCaramelLatteTxt.getText());
            int total = harga * jumlah;
            grandTotal += total;

            menuBuilder.append("Caramel Latte").append(", ");
            hargaBuilder.append(harga).append(", ");
            jumlahBuilder.append("x").append(jumlah).append(", ");

            SubTotalCaramelTxt.setText(String.valueOf(total));
        }

        // Americano
        if (!HargaAmericanoTxt.getText().isEmpty() && !JumlahAmericanoTxt.getText().isEmpty()) {
            int harga = Integer.parseInt(HargaAmericanoTxt.getText());
            int jumlah = Integer.parseInt(JumlahAmericanoTxt.getText());
            int total = harga * jumlah;
            grandTotal += total;

            menuBuilder.append("Americano").append(", ");
            hargaBuilder.append(harga).append(", ");
            jumlahBuilder.append("x").append(jumlah).append(", ");

            SubTotalAmericanoTxt.setText(String.valueOf(total));
        }

        // Matcha Latte
        if (!HargaMatchaLatteTxt.getText().isEmpty() && !JumlahMatchaLatteTxt.getText().isEmpty()) {
            int harga = Integer.parseInt(HargaMatchaLatteTxt.getText());
            int jumlah = Integer.parseInt(JumlahMatchaLatteTxt.getText());
            int total = harga * jumlah;
            grandTotal += total;

            menuBuilder.append("Matcha Latte").append(", ");
            hargaBuilder.append(harga).append(", ");
            jumlahBuilder.append("x").append(jumlah).append(", ");

            SubTotalMatchaTxt.setText(String.valueOf(total));
        }

        if (menuBuilder.length() > 0) {
            menuBuilder.setLength(menuBuilder.length() - 2);
            hargaBuilder.setLength(hargaBuilder.length() - 2);
            jumlahBuilder.setLength(jumlahBuilder.length() - 2);
        }

        // Tampilkan total semua
        TotalTxt.setText("Rp." + grandTotal);

        // Diskon dan total akhir
        int bayarTotal = grandTotal;
        String diskon = "0%";
        if (grandTotal > 300000) {
            diskon = "10%";
            bayarTotal = grandTotal - (grandTotal * 10 / 100);
        } else if (grandTotal > 200000) {
            diskon = "7%";
            bayarTotal = grandTotal - (grandTotal * 7 / 100);
        } else if (grandTotal > 100000) {
            diskon = "5%";
            bayarTotal = grandTotal - (grandTotal * 5 / 100);
        }
        DiskonTxt.setText(diskon);
        TotalBayarTxt.setText("Rp." + bayarTotal);

        // Tambahkan ke JTable
        DefaultTableModel model = (DefaultTableModel) MenungguTransaksiTabel.getModel();
        model.insertRow(0, new Object[]{
            namaPemesan,
            menuBuilder.toString(),
            hargaBuilder.toString(),
            jumlahBuilder.toString(),
            "Rp." + bayarTotal,
            metodepembayaran,
            "Menunggu Pembayaran"
        });

        // Simpan ke database
        try {
            Connection conn = Koneksidatabase.getConnection();
            String sql = "INSERT INTO pesanan (nama_pemesan, menu, harga, jumlah, total_bayar, metode_pembayaran, status_pembayaran) VALUES (?, ?, ?, ?, ?, ?, ?)";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaPemesan);
            pst.setString(2, menuBuilder.toString());
            pst.setString(3, hargaBuilder.toString());
            pst.setString(4, jumlahBuilder.toString());
            pst.setString(5, "Rp." + bayarTotal);
            pst.setString(6, metodepembayaran);
            pst.setString(7, "Menunggu Pembayaran");

            pst.executeUpdate();
            javax.swing.JOptionPane.showMessageDialog(this, "Pemesanan berhasil di konfirmasi!");
        } catch (SQLException e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
        }
    }//GEN-LAST:event_KonfirmasiButtonActionPerformed

    private void FreezyDutchCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FreezyDutchCbActionPerformed
        if (FreezyDutchCb.isSelected()) {
            HargaFreezyDutchTxt.setEnabled(true);
            JumlahFreezyDutchTxt.setEnabled(true);
            SubTotalFreezyTxt.setEnabled(true);

            HargaFreezyDutchTxt.setText("33000");
        } else {
            HargaFreezyDutchTxt.setText("");
            JumlahFreezyDutchTxt.setText("");
            SubTotalFreezyTxt.setText("");
        }
    }//GEN-LAST:event_FreezyDutchCbActionPerformed

    private void CaramelLatteCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaramelLatteCbActionPerformed
        if (CaramelLatteCb.isSelected()) {
            HargaCaramelLatteTxt.setEnabled(true);
            JumlahCaramelLatteTxt.setEnabled(true);
            SubTotalCaramelTxt.setEnabled(true);

            HargaCaramelLatteTxt.setText("28000");
        } else {
            HargaCaramelLatteTxt.setText("");
            JumlahCaramelLatteTxt.setText("");
            SubTotalCaramelTxt.setText("");;
        }
    }//GEN-LAST:event_CaramelLatteCbActionPerformed

    private void AmericanoCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AmericanoCbActionPerformed
        if (AmericanoCb.isSelected()) {
            HargaAmericanoTxt.setEnabled(true);
            JumlahAmericanoTxt.setEnabled(true);
            SubTotalAmericanoTxt.setEnabled(true);

            HargaAmericanoTxt.setText("18000");
        } else {
            HargaAmericanoTxt.setText("");
            JumlahAmericanoTxt.setText("");
            SubTotalAmericanoTxt.setText("");
        }
    }//GEN-LAST:event_AmericanoCbActionPerformed

    private void MatchaLatteCbActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MatchaLatteCbActionPerformed
        if (MatchaLatteCb.isSelected()) {
            HargaMatchaLatteTxt.setEnabled(true);
            JumlahMatchaLatteTxt.setEnabled(true);
            SubTotalMatchaTxt.setEnabled(true);

            HargaMatchaLatteTxt.setText("24000");
        } else {
            HargaMatchaLatteTxt.setText("");
            JumlahMatchaLatteTxt.setText("");
            SubTotalMatchaTxt.setText("");
        }
    }//GEN-LAST:event_MatchaLatteCbActionPerformed

    private void ProsesBayarButtonActionPerformed(java.awt.event.ActionEvent evt) {
        int selectedRow = MenungguTransaksiTabel.getSelectedRow();
        if (selectedRow == -1) {
            JOptionPane.showMessageDialog(this, "Pilih baris data terlebih dahulu!");
            return;
        }

        String namaPemesan = MenungguTransaksiTabel.getValueAt(selectedRow, 0).toString();
        String totalBayar = MenungguTransaksiTabel.getValueAt(selectedRow, 4).toString();

        try {
            Connection conn = Koneksidatabase.getConnection();
            // Update status di SQLite
            String sql = "UPDATE pesanan SET status_pembayaran='Sudah Bayar' WHERE nama_pemesan=? AND total_bayar=?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, namaPemesan);
            pst.setString(2, totalBayar);

            int rowsUpdated = pst.executeUpdate();
            if (rowsUpdated > 0) {
                JOptionPane.showMessageDialog(this, "Pembayaran Berhasil!");
                loadDataMenunggu();
                loadDataTerbayar();
            }
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Gagal Update: " + e.getMessage());
        }
    }

    private void MetodePembayaranCbxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MetodePembayaranCbxActionPerformed
        String metodepembayaran = (String) MetodePembayaranCbx.getSelectedItem();
        switch (metodepembayaran) {
            case "Cash" -> {
            }
            case "QRIS" -> {
            }
            case "GoPay" -> {
            }
            case "DANA" -> {
            }
        }
    }//GEN-LAST:event_MetodePembayaranCbxActionPerformed

    private void HargaMatchaLatteTxtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HargaMatchaLatteTxtActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_HargaMatchaLatteTxtActionPerformed

    private void KeluarButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_KeluarButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_KeluarButtonActionPerformed

    private void ResetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ResetButtonActionPerformed
        NamaPemesanTxt.setText("");
        HargaCaramelLatteTxt.setText("");
        JumlahCaramelLatteTxt.setText("");
        SubTotalCaramelTxt.setText("");
        HargaAmericanoTxt.setText("");
        JumlahAmericanoTxt.setText("");
        SubTotalAmericanoTxt.setText("");
        HargaFreezyDutchTxt.setText("");
        JumlahFreezyDutchTxt.setText("");
        SubTotalFreezyTxt.setText("");
        HargaMatchaLatteTxt.setText("");
        JumlahMatchaLatteTxt.setText("");
        SubTotalMatchaTxt.setText("");
        TotalTxt.setText("");
        DiskonTxt.setText("");
        TotalBayarTxt.setText("");
        MetodePembayaranCbx.setSelectedIndex(0);
        CaramelLatteCb.setSelected(false);
        AmericanoCb.setSelected(false);
        FreezyDutchCb.setSelected(false);
        MatchaLatteCb.setSelected(false);
    }//GEN-LAST:event_ResetButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AplikasiKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AplikasiKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AplikasiKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AplikasiKopi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AplikasiKopi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox AmericanoCb;
    private javax.swing.JCheckBox CaramelLatteCb;
    private javax.swing.JTextField DiskonTxt;
    private javax.swing.JCheckBox FreezyDutchCb;
    private javax.swing.JButton HapusButton;
    private javax.swing.JTextField HargaAmericanoTxt;
    private javax.swing.JTextField HargaCaramelLatteTxt;
    private javax.swing.JTextField HargaFreezyDutchTxt;
    private javax.swing.JTextField HargaMatchaLatteTxt;
    private javax.swing.JTextField JumlahAmericanoTxt;
    private javax.swing.JTextField JumlahCaramelLatteTxt;
    private javax.swing.JTextField JumlahFreezyDutchTxt;
    private javax.swing.JTextField JumlahMatchaLatteTxt;
    private javax.swing.JButton KeluarButton;
    private javax.swing.JButton KonfirmasiButton;
    private javax.swing.JCheckBox MatchaLatteCb;
    private javax.swing.JTable MenungguTransaksiTabel;
    private javax.swing.JComboBox<String> MetodePembayaranCbx;
    private javax.swing.JTextField NamaPemesanTxt;
    private javax.swing.JButton ProsesBayarButton;
    private javax.swing.JButton ResetButton;
    private javax.swing.JTextField SubTotalAmericanoTxt;
    private javax.swing.JTextField SubTotalCaramelTxt;
    private javax.swing.JTextField SubTotalFreezyTxt;
    private javax.swing.JTextField SubTotalMatchaTxt;
    private javax.swing.JTextField TotalBayarTxt;
    private javax.swing.JTextField TotalTxt;
    private javax.swing.JTable TransaksiTerbayarTabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane3;
    // End of variables declaration//GEN-END:variables

    private void loadDataMenunggu() {
        DefaultTableModel model = (DefaultTableModel) MenungguTransaksiTabel.getModel();
        model.setRowCount(0);
        try {
            Connection conn = Koneksidatabase.getConnection();
            if (conn != null) { // Tambahkan cek null agar tidak error lagi
                String sql = "SELECT * FROM pesanan WHERE status_pembayaran = 'Menunggu Pembayaran'";
                PreparedStatement pst = conn.prepareStatement(sql);
                ResultSet rs = pst.executeQuery();
                while (rs.next()) {
                    model.addRow(new Object[]{
                        rs.getString("nama_pemesan"), rs.getString("menu"),
                        rs.getString("harga"), rs.getString("jumlah"),
                        rs.getString("total_bayar"), rs.getString("metode_pembayaran"),
                        rs.getString("status_pembayaran")
                    });
                }
            }
        } catch (SQLException e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    private void loadDataTerbayar() {
        DefaultTableModel model = (DefaultTableModel) TransaksiTerbayarTabel.getModel();
        model.setRowCount(0);
        try {
            Connection conn = Koneksidatabase.getConnection();
            String sql = "SELECT * FROM pesanan WHERE status_pembayaran = 'Sudah Bayar'";
            PreparedStatement pst = conn.prepareStatement(sql);
            ResultSet rs = pst.executeQuery();
            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("nama_pemesan"), rs.getString("menu"),
                    rs.getString("harga"), rs.getString("jumlah"),
                    rs.getString("total_bayar"), rs.getString("metode_pembayaran"),
                    rs.getString("status_pembayaran")
                });
            }
        } catch (SQLException e) {
            System.out.println("Error memuat data terbayar: " + e.getMessage());
        }
    }
}